package tui

import (
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"charm.land/bubbles/v2/textinput"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
)

type authType int

const (
	authNone authType = iota
	authBearer
	authJWTBearer
	authBasic
	authDigest
	authAPIKey
	authAWSSignatureV4
	authOAuth2ClientCredentials
	authOAuth2Password
	authOAuth2RefreshToken
	authOAuth2AuthorizationCode
	authHawk
	authNTLM
	authOAuth1
	authTypeCount
)

type apiKeyLocation int

const (
	apiKeyHeader apiKeyLocation = iota
	apiKeyQuery
)

type authConfig struct {
	typeID                 authType
	bearerToken            string
	jwtAlgorithm           string
	jwtKey                 string
	jwtSecretBase64        bool
	jwtPayload             string
	jwtHeaders             string
	jwtPrefix              string
	jwtLocation            apiKeyLocation
	jwtQueryName           string
	username               string
	password               string
	apiKeyName             string
	apiKeyValue            string
	apiKeyLocation         apiKeyLocation
	oauthTokenURL          string
	oauthAuthorizationURL  string
	oauthClientID          string
	oauthClientSecret      string
	oauthScope             string
	oauthRefreshToken      string
	oauthCallbackURL       string
	oauthAccessToken       string
	oauthTokenType         string
	oauthAccessTokenExpiry int64
	oauthClientAuth        string
	oauthPKCE              bool
	hawkID                 string
	hawkKey                string
	hawkAlgorithm          string
	hawkExt                string
	ntlmDomain             string
	ntlmWorkstation        string
	oauth1ConsumerKey      string
	oauth1ConsumerSecret   string
	oauth1Token            string
	oauth1TokenSecret      string
	oauth1PrivateKey       string
	oauth1SignatureMethod  string
	oauth1Realm            string
	oauth1Callback         string
	oauth1Verifier         string
	oauth1IncludeBodyHash  bool
	oauth1Location         apiKeyLocation
	awsAccessKey           string
	awsSecretKey           string
	awsRegion              string
	awsService             string
	awsSessionToken        string
}

type authPane struct {
	config                authConfig
	cursor                int
	focused               bool
	secretsVisible        bool
	width                 int
	bearer                textinput.Model
	jwtKey                textinput.Model
	jwtPayload            textinput.Model
	jwtHeaders            textinput.Model
	jwtPrefix             textinput.Model
	jwtQueryName          textinput.Model
	username              textinput.Model
	password              textinput.Model
	keyName               textinput.Model
	keyValue              textinput.Model
	oauthTokenURL         textinput.Model
	oauthAuthorizationURL textinput.Model
	oauthClientID         textinput.Model
	oauthClientSecret     textinput.Model
	oauthScope            textinput.Model
	oauthRefreshToken     textinput.Model
	oauthCallbackURL      textinput.Model
	oauthAccessToken      textinput.Model
	hawkID                textinput.Model
	hawkKey               textinput.Model
	hawkExt               textinput.Model
	ntlmDomain            textinput.Model
	ntlmWorkstation       textinput.Model
	oauth1ConsumerKey     textinput.Model
	oauth1ConsumerSecret  textinput.Model
	oauth1Token           textinput.Model
	oauth1TokenSecret     textinput.Model
	oauth1PrivateKey      textinput.Model
	oauth1Realm           textinput.Model
	oauth1Callback        textinput.Model
	oauth1Verifier        textinput.Model
	awsAccessKey          textinput.Model
	awsSecretKey          textinput.Model
	awsRegion             textinput.Model
	awsService            textinput.Model
	awsSessionToken       textinput.Model
}

func newAuthPane() authPane {
	newInput := func(placeholder string) textinput.Model {
		input := textinput.New()
		input.Prompt = ""
		input.Placeholder = placeholder
		input.CharLimit = 4096
		input.Blur()
		return input
	}
	newSecretInput := func(placeholder string) textinput.Model {
		input := newInput(placeholder)
		input.EchoMode = textinput.EchoPassword
		input.EchoCharacter = '•'
		return input
	}

	bearer := newSecretInput("token")
	jwtKey := newSecretInput("secret, private-key path, or PEM")
	password := newSecretInput("password")
	keyValue := newSecretInput("value")
	oauthSecret := newSecretInput("client secret")
	oauthRefreshToken := newSecretInput("refresh token")
	oauthAccessToken := newSecretInput("access token (generated by g)")
	hawkKey := newSecretInput("shared key")
	oauth1ConsumerSecret := newSecretInput("consumer secret")
	oauth1Token := newSecretInput("access token (optional)")
	oauth1TokenSecret := newSecretInput("token secret")
	oauth1PrivateKey := newSecretInput("RSA private-key path or PEM")
	awsSecret := newSecretInput("secret access key")
	awsSessionToken := newSecretInput("session token (optional)")

	jwtPayload := newInput(`{"sub":"user"}`)
	jwtPayload.SetValue("{}")
	jwtHeaders := newInput(`{"kid":"key-id"}`)
	jwtHeaders.SetValue("{}")
	jwtPrefix := newInput("Bearer")
	jwtPrefix.SetValue("Bearer")
	jwtQueryName := newInput("jwt")
	jwtQueryName.SetValue("jwt")

	return authPane{
		config:                authConfig{jwtAlgorithm: "HS256", jwtPayload: "{}", jwtHeaders: "{}", jwtPrefix: "Bearer", jwtQueryName: "jwt", hawkAlgorithm: "sha256", oauth1SignatureMethod: "HMAC-SHA1", oauthCallbackURL: "http://127.0.0.1:8085/callback", oauthClientAuth: "basic", oauthPKCE: true},
		bearer:                bearer,
		jwtKey:                jwtKey,
		jwtPayload:            jwtPayload,
		jwtHeaders:            jwtHeaders,
		jwtPrefix:             jwtPrefix,
		jwtQueryName:          jwtQueryName,
		username:              newInput("username"),
		password:              password,
		keyName:               newInput("X-API-Key"),
		keyValue:              keyValue,
		oauthTokenURL:         newInput("https://identity.example/oauth/token"),
		oauthAuthorizationURL: newInput("https://identity.example/oauth/authorize"),
		oauthClientID:         newInput("client ID"),
		oauthClientSecret:     oauthSecret,
		oauthScope:            newInput("space-separated scopes (optional)"),
		oauthRefreshToken:     oauthRefreshToken,
		oauthCallbackURL:      newInput("http://127.0.0.1:8085/callback"),
		oauthAccessToken:      oauthAccessToken,
		hawkID:                newInput("credential ID"),
		hawkKey:               hawkKey,
		hawkExt:               newInput("application data (optional)"),
		ntlmDomain:            newInput("user domain (optional)"),
		ntlmWorkstation:       newInput("workstation (optional)"),
		oauth1ConsumerKey:     newInput("consumer key"),
		oauth1ConsumerSecret:  oauth1ConsumerSecret,
		oauth1Token:           oauth1Token,
		oauth1TokenSecret:     oauth1TokenSecret,
		oauth1PrivateKey:      oauth1PrivateKey,
		oauth1Realm:           newInput("realm (optional)"),
		oauth1Callback:        newInput("callback URL (optional)"),
		oauth1Verifier:        newInput("verifier (optional)"),
		awsAccessKey:          newInput("access key ID"),
		awsSecretKey:          awsSecret,
		awsRegion:             newInput("us-east-1"),
		awsService:            newInput("execute-api"),
		awsSessionToken:       awsSessionToken,
	}
}

func (a *authPane) Config() authConfig {
	a.syncConfig()
	return a.config
}

func (a *authPane) secretInputs() []*textinput.Model {
	return []*textinput.Model{
		&a.bearer,
		&a.jwtKey,
		&a.password,
		&a.keyValue,
		&a.oauthClientSecret,
		&a.oauthRefreshToken,
		&a.oauthAccessToken,
		&a.hawkKey,
		&a.oauth1ConsumerSecret,
		&a.oauth1Token,
		&a.oauth1TokenSecret,
		&a.oauth1PrivateKey,
		&a.awsSecretKey,
		&a.awsSessionToken,
	}
}

func (a *authPane) setSecretsVisible(visible bool) {
	a.secretsVisible = visible
	mode := textinput.EchoPassword
	if visible {
		mode = textinput.EchoNormal
	}
	for _, input := range a.secretInputs() {
		input.EchoMode = mode
	}
}

func (a *authPane) SetConfig(config authConfig) {
	if config.jwtAlgorithm == "" {
		config.jwtAlgorithm = "HS256"
	}
	if config.jwtPayload == "" {
		config.jwtPayload = "{}"
	}
	if config.jwtHeaders == "" {
		config.jwtHeaders = "{}"
	}
	if config.jwtPrefix == "" {
		config.jwtPrefix = "Bearer"
	}
	if config.jwtQueryName == "" {
		config.jwtQueryName = "jwt"
	}
	if config.hawkAlgorithm == "" {
		config.hawkAlgorithm = "sha256"
	}
	if config.oauth1SignatureMethod == "" {
		config.oauth1SignatureMethod = "HMAC-SHA1"
	}
	if config.oauthCallbackURL == "" {
		config.oauthCallbackURL = "http://127.0.0.1:8085/callback"
	}
	if config.oauthClientAuth == "" {
		config.oauthClientAuth = "basic"
	}
	a.config = config
	a.bearer.SetValue(config.bearerToken)
	a.jwtKey.SetValue(config.jwtKey)
	a.jwtPayload.SetValue(config.jwtPayload)
	a.jwtHeaders.SetValue(config.jwtHeaders)
	a.jwtPrefix.SetValue(config.jwtPrefix)
	a.jwtQueryName.SetValue(config.jwtQueryName)
	a.username.SetValue(config.username)
	a.password.SetValue(config.password)
	a.keyName.SetValue(config.apiKeyName)
	a.keyValue.SetValue(config.apiKeyValue)
	a.oauthTokenURL.SetValue(config.oauthTokenURL)
	a.oauthAuthorizationURL.SetValue(config.oauthAuthorizationURL)
	a.oauthClientID.SetValue(config.oauthClientID)
	a.oauthClientSecret.SetValue(config.oauthClientSecret)
	a.oauthScope.SetValue(config.oauthScope)
	a.oauthRefreshToken.SetValue(config.oauthRefreshToken)
	a.oauthCallbackURL.SetValue(config.oauthCallbackURL)
	a.oauthAccessToken.SetValue(config.oauthAccessToken)
	a.hawkID.SetValue(config.hawkID)
	a.hawkKey.SetValue(config.hawkKey)
	a.hawkExt.SetValue(config.hawkExt)
	a.ntlmDomain.SetValue(config.ntlmDomain)
	a.ntlmWorkstation.SetValue(config.ntlmWorkstation)
	a.oauth1ConsumerKey.SetValue(config.oauth1ConsumerKey)
	a.oauth1ConsumerSecret.SetValue(config.oauth1ConsumerSecret)
	a.oauth1Token.SetValue(config.oauth1Token)
	a.oauth1TokenSecret.SetValue(config.oauth1TokenSecret)
	a.oauth1PrivateKey.SetValue(config.oauth1PrivateKey)
	a.oauth1Realm.SetValue(config.oauth1Realm)
	a.oauth1Callback.SetValue(config.oauth1Callback)
	a.oauth1Verifier.SetValue(config.oauth1Verifier)
	a.awsAccessKey.SetValue(config.awsAccessKey)
	a.awsSecretKey.SetValue(config.awsSecretKey)
	a.awsRegion.SetValue(config.awsRegion)
	a.awsService.SetValue(config.awsService)
	a.awsSessionToken.SetValue(config.awsSessionToken)
	a.cursor = 0
	a.Blur()
}

func (a *authPane) syncConfig() {
	a.config.bearerToken = a.bearer.Value()
	a.config.jwtKey = a.jwtKey.Value()
	a.config.jwtPayload = a.jwtPayload.Value()
	a.config.jwtHeaders = a.jwtHeaders.Value()
	a.config.jwtPrefix = a.jwtPrefix.Value()
	a.config.jwtQueryName = a.jwtQueryName.Value()
	a.config.username = a.username.Value()
	a.config.password = a.password.Value()
	a.config.apiKeyName = a.keyName.Value()
	a.config.apiKeyValue = a.keyValue.Value()
	a.config.oauthTokenURL = a.oauthTokenURL.Value()
	a.config.oauthAuthorizationURL = a.oauthAuthorizationURL.Value()
	a.config.oauthClientID = a.oauthClientID.Value()
	a.config.oauthClientSecret = a.oauthClientSecret.Value()
	a.config.oauthScope = a.oauthScope.Value()
	a.config.oauthRefreshToken = a.oauthRefreshToken.Value()
	a.config.oauthCallbackURL = a.oauthCallbackURL.Value()
	a.config.oauthAccessToken = a.oauthAccessToken.Value()
	a.config.hawkID = a.hawkID.Value()
	a.config.hawkKey = a.hawkKey.Value()
	a.config.hawkExt = a.hawkExt.Value()
	a.config.ntlmDomain = a.ntlmDomain.Value()
	a.config.ntlmWorkstation = a.ntlmWorkstation.Value()
	a.config.oauth1ConsumerKey = a.oauth1ConsumerKey.Value()
	a.config.oauth1ConsumerSecret = a.oauth1ConsumerSecret.Value()
	a.config.oauth1Token = a.oauth1Token.Value()
	a.config.oauth1TokenSecret = a.oauth1TokenSecret.Value()
	a.config.oauth1PrivateKey = a.oauth1PrivateKey.Value()
	a.config.oauth1Realm = a.oauth1Realm.Value()
	a.config.oauth1Callback = a.oauth1Callback.Value()
	a.config.oauth1Verifier = a.oauth1Verifier.Value()
	a.config.awsAccessKey = a.awsAccessKey.Value()
	a.config.awsSecretKey = a.awsSecretKey.Value()
	a.config.awsRegion = a.awsRegion.Value()
	a.config.awsService = a.awsService.Value()
	a.config.awsSessionToken = a.awsSessionToken.Value()
}

func (a authPane) Editable() bool { return a.fieldCount() > 0 }

func (a authPane) fieldCount() int {
	switch a.config.typeID {
	case authBearer:
		return 1
	case authJWTBearer, authAWSSignatureV4:
		return 5
	case authBasic, authDigest, authAPIKey:
		return 2
	case authOAuth2ClientCredentials:
		return 4
	case authOAuth2Password:
		return 6
	case authOAuth2RefreshToken:
		return 5
	case authOAuth2AuthorizationCode:
		return 8
	case authHawk:
		return 3
	case authNTLM:
		return 4
	case authOAuth1:
		return 8
	default:
		return 0
	}
}

func (a *authPane) Focus() { a.focused = true }

func (a *authPane) Blur() {
	a.focused = false
	a.blurAll()
	a.setSecretsVisible(false)
}

func (a *authPane) blurAll() {
	a.bearer.Blur()
	a.jwtKey.Blur()
	a.jwtPayload.Blur()
	a.jwtHeaders.Blur()
	a.jwtPrefix.Blur()
	a.jwtQueryName.Blur()
	a.username.Blur()
	a.password.Blur()
	a.keyName.Blur()
	a.keyValue.Blur()
	a.oauthTokenURL.Blur()
	a.oauthAuthorizationURL.Blur()
	a.oauthClientID.Blur()
	a.oauthClientSecret.Blur()
	a.oauthScope.Blur()
	a.oauthRefreshToken.Blur()
	a.oauthCallbackURL.Blur()
	a.oauthAccessToken.Blur()
	a.hawkID.Blur()
	a.hawkKey.Blur()
	a.hawkExt.Blur()
	a.ntlmDomain.Blur()
	a.ntlmWorkstation.Blur()
	a.oauth1ConsumerKey.Blur()
	a.oauth1ConsumerSecret.Blur()
	a.oauth1Token.Blur()
	a.oauth1TokenSecret.Blur()
	a.oauth1PrivateKey.Blur()
	a.oauth1Realm.Blur()
	a.oauth1Callback.Blur()
	a.oauth1Verifier.Blur()
	a.awsAccessKey.Blur()
	a.awsSecretKey.Blur()
	a.awsRegion.Blur()
	a.awsService.Blur()
	a.awsSessionToken.Blur()
}

func (a *authPane) FocusCurrent() tea.Cmd {
	a.blurAll()
	input := a.currentInput()
	if input == nil {
		return nil
	}
	return input.Focus()
}

func (a *authPane) currentInput() *textinput.Model {
	switch a.config.typeID {
	case authBearer:
		return &a.bearer
	case authJWTBearer:
		switch a.cursor {
		case 0:
			return &a.jwtKey
		case 1:
			return &a.jwtPayload
		case 2:
			return &a.jwtHeaders
		case 3:
			return &a.jwtPrefix
		default:
			return &a.jwtQueryName
		}
	case authBasic, authDigest:
		if a.cursor == 0 {
			return &a.username
		}
		return &a.password
	case authAPIKey:
		if a.cursor == 0 {
			return &a.keyName
		}
		return &a.keyValue
	case authOAuth2ClientCredentials, authOAuth2Password, authOAuth2RefreshToken:
		switch a.cursor {
		case 0:
			return &a.oauthTokenURL
		case 1:
			return &a.oauthClientID
		case 2:
			return &a.oauthClientSecret
		case 3:
			return &a.oauthScope
		case 4:
			if a.config.typeID == authOAuth2RefreshToken {
				return &a.oauthRefreshToken
			}
			return &a.username
		default:
			return &a.password
		}
	case authOAuth2AuthorizationCode:
		switch a.cursor {
		case 0:
			return &a.oauthAuthorizationURL
		case 1:
			return &a.oauthTokenURL
		case 2:
			return &a.oauthClientID
		case 3:
			return &a.oauthClientSecret
		case 4:
			return &a.oauthScope
		case 5:
			return &a.oauthCallbackURL
		case 6:
			return &a.oauthAccessToken
		default:
			return &a.oauthRefreshToken
		}
	case authHawk:
		switch a.cursor {
		case 0:
			return &a.hawkID
		case 1:
			return &a.hawkKey
		default:
			return &a.hawkExt
		}
	case authNTLM:
		switch a.cursor {
		case 0:
			return &a.username
		case 1:
			return &a.password
		case 2:
			return &a.ntlmDomain
		default:
			return &a.ntlmWorkstation
		}
	case authOAuth1:
		switch a.cursor {
		case 0:
			return &a.oauth1ConsumerKey
		case 1:
			return &a.oauth1ConsumerSecret
		case 2:
			return &a.oauth1Token
		case 3:
			return &a.oauth1TokenSecret
		case 4:
			return &a.oauth1PrivateKey
		case 5:
			return &a.oauth1Realm
		case 6:
			return &a.oauth1Callback
		default:
			return &a.oauth1Verifier
		}
	case authAWSSignatureV4:
		switch a.cursor {
		case 0:
			return &a.awsAccessKey
		case 1:
			return &a.awsSecretKey
		case 2:
			return &a.awsRegion
		case 3:
			return &a.awsService
		default:
			return &a.awsSessionToken
		}
	default:
		return nil
	}
}

func (a *authPane) UpdateInsert(msg tea.Msg) tea.Cmd {
	input := a.currentInput()
	if input == nil {
		return nil
	}
	var cmd tea.Cmd
	*input, cmd = input.Update(msg)
	return cmd
}

func (a *authPane) UpdateNormal(keyStr string) {
	switch keyStr {
	case "o":
		a.syncConfig()
		a.config.typeID = (a.config.typeID + 1) % authTypeCount
		a.cursor = 0
		a.blurAll()
	case "j":
		if a.cursor < a.fieldCount()-1 {
			a.cursor++
		}
	case "k":
		if a.cursor > 0 {
			a.cursor--
		}
	case " ", "space":
		switch a.config.typeID {
		case authAPIKey:
			a.config.apiKeyLocation = (a.config.apiKeyLocation + 1) % 2
		case authJWTBearer:
			a.config.jwtLocation = (a.config.jwtLocation + 1) % 2
		case authOAuth1:
			a.config.oauth1Location = (a.config.oauth1Location + 1) % 2
		}
	case "h", "left":
		switch a.config.typeID {
		case authJWTBearer:
			a.cycleJWTAlgorithm(-1)
		case authHawk:
			a.cycleHawkAlgorithm()
		case authOAuth1:
			a.cycleOAuth1Signature(-1)
		}
	case "l", "right":
		switch a.config.typeID {
		case authJWTBearer:
			a.cycleJWTAlgorithm(1)
		case authHawk:
			a.cycleHawkAlgorithm()
		case authOAuth1:
			a.cycleOAuth1Signature(1)
		}
	case "b":
		if a.config.typeID == authJWTBearer && strings.HasPrefix(a.config.jwtAlgorithm, "HS") {
			a.config.jwtSecretBase64 = !a.config.jwtSecretBase64
		} else if a.config.typeID == authOAuth1 {
			a.config.oauth1IncludeBodyHash = !a.config.oauth1IncludeBodyHash
		}
	case "p":
		if a.config.typeID == authOAuth2AuthorizationCode {
			a.config.oauthPKCE = !a.config.oauthPKCE
		}
	case "v":
		a.setSecretsVisible(!a.secretsVisible)
	case "a":
		if a.config.typeID == authOAuth2AuthorizationCode {
			styles := []string{"basic", "body", "none"}
			index := 0
			for candidate, style := range styles {
				if style == a.config.oauthClientAuth {
					index = candidate
					break
				}
			}
			a.config.oauthClientAuth = styles[(index+1)%len(styles)]
		}
	}
}

func (a *authPane) cycleHawkAlgorithm() {
	if a.config.hawkAlgorithm == "sha1" {
		a.config.hawkAlgorithm = "sha256"
	} else {
		a.config.hawkAlgorithm = "sha1"
	}
}

func (a *authPane) cycleOAuth1Signature(direction int) {
	methods := []string{"HMAC-SHA1", "HMAC-SHA256", "RSA-SHA1", "PLAINTEXT"}
	index := 0
	for candidate, method := range methods {
		if method == a.config.oauth1SignatureMethod {
			index = candidate
			break
		}
	}
	a.config.oauth1SignatureMethod = methods[(index+direction+len(methods))%len(methods)]
}

func (a *authPane) cycleJWTAlgorithm(direction int) {
	index := 0
	for candidate, algorithm := range jwtAlgorithms {
		if algorithm == a.config.jwtAlgorithm {
			index = candidate
			break
		}
	}
	index = (index + direction + len(jwtAlgorithms)) % len(jwtAlgorithms)
	a.config.jwtAlgorithm = jwtAlgorithms[index]
}

func (a *authPane) SetWidth(width int) {
	a.width = width
	inputWidth := width - 14
	if inputWidth < 10 {
		inputWidth = 10
	}
	for _, input := range []*textinput.Model{&a.bearer, &a.jwtKey, &a.jwtPayload, &a.jwtHeaders, &a.jwtPrefix, &a.jwtQueryName, &a.username, &a.password, &a.keyName, &a.keyValue, &a.oauthAuthorizationURL, &a.oauthTokenURL, &a.oauthClientID, &a.oauthClientSecret, &a.oauthScope, &a.oauthCallbackURL, &a.oauthAccessToken, &a.oauthRefreshToken, &a.hawkID, &a.hawkKey, &a.hawkExt, &a.ntlmDomain, &a.ntlmWorkstation, &a.oauth1ConsumerKey, &a.oauth1ConsumerSecret, &a.oauth1Token, &a.oauth1TokenSecret, &a.oauth1PrivateKey, &a.oauth1Realm, &a.oauth1Callback, &a.oauth1Verifier, &a.awsAccessKey, &a.awsSecretKey, &a.awsRegion, &a.awsService, &a.awsSessionToken} {
		input.SetWidth(inputWidth)
	}
	awsLocationWidth := max(8, (inputWidth-12)/2)
	a.awsRegion.SetWidth(awsLocationWidth)
	a.awsService.SetWidth(awsLocationWidth)
}

func (a authPane) View(heights ...int) string {
	typeName := map[authType]string{
		authNone: "No Auth", authBearer: "Bearer Token", authJWTBearer: "JWT Bearer", authBasic: "Basic Auth", authDigest: "Digest Auth", authAPIKey: "API Key", authAWSSignatureV4: "AWS Signature v4", authOAuth2ClientCredentials: "OAuth 2 Client Credentials", authOAuth2Password: "OAuth 2 Password Credentials", authOAuth2RefreshToken: "OAuth 2 Refresh Token", authOAuth2AuthorizationCode: "OAuth 2 Authorization Code", authHawk: "Hawk", authNTLM: "NTLM", authOAuth1: "OAuth 1.0",
	}[a.config.typeID]
	lines := []string{headerStyle.Render("Type: ") + typeName + hintStyle.Render("  o:cycle")}

	switch a.config.typeID {
	case authNone:
		lines = append(lines, hintStyle.Render("No authorization will be added to the request."))
	case authBearer:
		lines = append(lines, a.renderInputRow(0, "Token", a.bearer.View()))
	case authJWTBearer:
		location := "Request Header"
		if a.config.jwtLocation == apiKeyQuery {
			location = "Query Param"
		}
		base64State := "plain secret"
		if a.config.jwtSecretBase64 {
			base64State = "base64 secret"
		}
		lines = append(lines,
			"  Algorithm: "+activeCellStyle.Render(a.config.jwtAlgorithm)+hintStyle.Render("  h/l:change"),
			a.renderInputRow(0, "Key", a.jwtKey.View()),
			a.renderInputRow(1, "Payload", a.jwtPayload.View()),
			a.renderInputRow(2, "Headers", a.jwtHeaders.View()),
			a.renderInputRow(3, "Prefix", a.jwtPrefix.View()),
			a.renderInputRow(4, "Query key", a.jwtQueryName.View()),
			"  Add to: "+activeCellStyle.Render(location)+hintStyle.Render("  space:toggle  b:"+base64State),
		)
	case authBasic, authDigest:
		lines = append(lines,
			a.renderInputRow(0, "Username", a.username.View()),
			a.renderInputRow(1, "Password", a.password.View()),
		)
	case authAPIKey:
		location := "Header"
		if a.config.apiKeyLocation == apiKeyQuery {
			location = "Query Params"
		}
		lines = append(lines,
			a.renderInputRow(0, "Key", a.keyName.View()),
			a.renderInputRow(1, "Value", a.keyValue.View()),
			"  Add to: "+activeCellStyle.Render(location)+hintStyle.Render("  space:toggle"),
		)
	case authOAuth2ClientCredentials:
		lines = append(lines,
			a.renderInputRow(0, "Token URL", a.oauthTokenURL.View()),
			a.renderInputRow(1, "Client ID", a.oauthClientID.View()),
			a.renderInputRow(2, "Secret", a.oauthClientSecret.View()),
			a.renderInputRow(3, "Scope", a.oauthScope.View()),
		)
	case authOAuth2Password:
		lines = append(lines,
			a.renderInputRow(0, "Token URL", a.oauthTokenURL.View()),
			a.renderInputRow(1, "Client ID", a.oauthClientID.View()),
			a.renderInputRow(2, "Secret", a.oauthClientSecret.View()),
			a.renderInputRow(3, "Scope", a.oauthScope.View()),
			a.renderInputRow(4, "Username", a.username.View()),
			a.renderInputRow(5, "Password", a.password.View()),
		)
	case authOAuth2RefreshToken:
		lines = append(lines,
			a.renderInputRow(0, "Token URL", a.oauthTokenURL.View()),
			a.renderInputRow(1, "Client ID", a.oauthClientID.View()),
			a.renderInputRow(2, "Secret", a.oauthClientSecret.View()),
			a.renderInputRow(3, "Scope", a.oauthScope.View()),
			a.renderInputRow(4, "Refresh", a.oauthRefreshToken.View()),
		)
	case authOAuth2AuthorizationCode:
		pkce := "disabled"
		if a.config.oauthPKCE {
			pkce = "S256"
		}
		lines = append(lines,
			a.renderInputRow(0, "Auth URL", a.oauthAuthorizationURL.View()),
			a.renderInputRow(1, "Token URL", a.oauthTokenURL.View()),
			a.renderInputRow(2, "Client ID", a.oauthClientID.View()),
			a.renderInputRow(3, "Secret", a.oauthClientSecret.View()),
			a.renderInputRow(4, "Scope", a.oauthScope.View()),
			a.renderInputRow(5, "Callback", a.oauthCallbackURL.View()),
			a.renderInputRow(6, "Access", a.oauthAccessToken.View()),
			a.renderInputRow(7, "Refresh", a.oauthRefreshToken.View()),
			"  PKCE: "+activeCellStyle.Render(pkce)+hintStyle.Render("  p:toggle")+"  Client auth: "+activeCellStyle.Render(a.config.oauthClientAuth)+hintStyle.Render("  a:cycle  g:get token"),
		)
	case authHawk:
		lines = append(lines,
			"  Algorithm: "+activeCellStyle.Render(a.config.hawkAlgorithm)+hintStyle.Render("  h/l:change"),
			a.renderInputRow(0, "Auth ID", a.hawkID.View()),
			a.renderInputRow(1, "Auth Key", a.hawkKey.View()),
			a.renderInputRow(2, "Ext", a.hawkExt.View()),
		)
	case authNTLM:
		lines = append(lines,
			a.renderInputRow(0, "Username", a.username.View()),
			a.renderInputRow(1, "Password", a.password.View()),
			a.renderInputRow(2, "Domain", a.ntlmDomain.View()),
			a.renderInputRow(3, "Workstation", a.ntlmWorkstation.View()),
		)
	case authOAuth1:
		location := "Request Header"
		if a.config.oauth1Location == apiKeyQuery {
			location = "Body & Query"
		}
		lines = append(lines,
			"  Signature: "+activeCellStyle.Render(a.config.oauth1SignatureMethod)+hintStyle.Render("  h/l:change"),
			a.renderInputRow(0, "Consumer", a.oauth1ConsumerKey.View()),
			a.renderInputRow(1, "Secret", a.oauth1ConsumerSecret.View()),
			a.renderInputRow(2, "Token", a.oauth1Token.View()),
			a.renderInputRow(3, "Token secret", a.oauth1TokenSecret.View()),
			a.renderInputRow(4, "Private key", a.oauth1PrivateKey.View()),
			a.renderInputRow(5, "Realm", a.oauth1Realm.View()),
			a.renderInputRow(6, "Callback", a.oauth1Callback.View()),
			a.renderInputRow(7, "Verifier", a.oauth1Verifier.View()),
			"  Add to: "+activeCellStyle.Render(location)+hintStyle.Render("  space:toggle"),
			"  Body hash: "+activeCellStyle.Render(strconv.FormatBool(a.config.oauth1IncludeBodyHash))+hintStyle.Render("  b:toggle"),
		)
	case authAWSSignatureV4:
		lines = append(lines,
			a.renderInputRow(0, "Access ID", a.awsAccessKey.View()),
			a.renderInputRow(1, "Secret", a.awsSecretKey.View()),
			a.renderAWSLocationRow(),
			a.renderInputRow(4, "Session", a.awsSessionToken.View()),
		)
	}
	secretHint := ""
	if a.config.typeID != authNone {
		secretHint = "  v:reveal secrets"
		if a.secretsVisible {
			secretHint = "  v:hide secrets"
		}
	}
	lines = append(lines, hintStyle.Render(" jk:move  i:edit  esc:normal"+secretHint))
	height := len(lines)
	if len(heights) > 0 {
		height = heights[0]
	}
	return renderCursorViewport(lines, a.activeLine(), height)
}

func (a authPane) activeLine() int {
	switch a.config.typeID {
	case authBearer:
		return 1
	case authJWTBearer:
		return a.cursor + 2
	case authBasic, authDigest, authAPIKey,
		authOAuth2ClientCredentials, authOAuth2Password, authOAuth2RefreshToken,
		authOAuth2AuthorizationCode, authNTLM:
		return a.cursor + 1
	case authHawk, authOAuth1:
		return a.cursor + 2
	case authAWSSignatureV4:
		switch a.cursor {
		case 0:
			return 1
		case 1:
			return 2
		case 2, 3:
			return 3
		default:
			return 4
		}
	default:
		return 1
	}
}

func (a authPane) renderAWSLocationRow() string {
	prefix := "  "
	if a.focused && (a.cursor == 2 || a.cursor == 3) {
		prefix = activeCellStyle.Render("> ")
	}
	regionLabel := "Region:"
	serviceLabel := "Service:"
	if a.focused && a.cursor == 2 {
		regionLabel = activeCellStyle.Render(regionLabel)
	}
	if a.focused && a.cursor == 3 {
		serviceLabel = activeCellStyle.Render(serviceLabel)
	}
	return prefix + regionLabel + " " + a.awsRegion.View() + "  " + serviceLabel + " " + a.awsService.View()
}

func (a authPane) renderInputRow(index int, label, value string) string {
	prefix := "  "
	if a.focused && a.cursor == index {
		prefix = activeCellStyle.Render("> ")
	}
	return prefix + lipgloss.NewStyle().Width(10).Render(label+":") + value
}

func (c authConfig) applyQuery(values url.Values) error {
	if c.typeID == authAPIKey && c.apiKeyLocation == apiKeyQuery && strings.TrimSpace(c.apiKeyName) != "" {
		values.Add(strings.TrimSpace(c.apiKeyName), c.apiKeyValue)
	}
	if c.typeID == authJWTBearer && c.jwtLocation == apiKeyQuery {
		token, err := generateJWT(c)
		if err != nil {
			return err
		}
		name := strings.TrimSpace(c.jwtQueryName)
		if name == "" {
			name = "jwt"
		}
		values.Add(name, token)
	}
	return nil
}

func (c authConfig) resolved(resolver *variableResolver) authConfig {
	c.bearerToken = resolver.Resolve(c.bearerToken)
	c.jwtKey = resolver.Resolve(c.jwtKey)
	c.jwtPayload = resolver.Resolve(c.jwtPayload)
	c.jwtHeaders = resolver.Resolve(c.jwtHeaders)
	c.jwtPrefix = resolver.Resolve(c.jwtPrefix)
	c.jwtQueryName = resolver.Resolve(c.jwtQueryName)
	c.username = resolver.Resolve(c.username)
	c.password = resolver.Resolve(c.password)
	c.apiKeyName = resolver.Resolve(c.apiKeyName)
	c.apiKeyValue = resolver.Resolve(c.apiKeyValue)
	c.oauthTokenURL = resolver.Resolve(c.oauthTokenURL)
	c.oauthAuthorizationURL = resolver.Resolve(c.oauthAuthorizationURL)
	c.oauthClientID = resolver.Resolve(c.oauthClientID)
	c.oauthClientSecret = resolver.Resolve(c.oauthClientSecret)
	c.oauthScope = resolver.Resolve(c.oauthScope)
	c.oauthRefreshToken = resolver.Resolve(c.oauthRefreshToken)
	c.oauthCallbackURL = resolver.Resolve(c.oauthCallbackURL)
	c.oauthAccessToken = resolver.Resolve(c.oauthAccessToken)
	c.hawkID = resolver.Resolve(c.hawkID)
	c.hawkKey = resolver.Resolve(c.hawkKey)
	c.hawkExt = resolver.Resolve(c.hawkExt)
	c.ntlmDomain = resolver.Resolve(c.ntlmDomain)
	c.ntlmWorkstation = resolver.Resolve(c.ntlmWorkstation)
	c.oauth1ConsumerKey = resolver.Resolve(c.oauth1ConsumerKey)
	c.oauth1ConsumerSecret = resolver.Resolve(c.oauth1ConsumerSecret)
	c.oauth1Token = resolver.Resolve(c.oauth1Token)
	c.oauth1TokenSecret = resolver.Resolve(c.oauth1TokenSecret)
	c.oauth1PrivateKey = resolver.Resolve(c.oauth1PrivateKey)
	c.oauth1Realm = resolver.Resolve(c.oauth1Realm)
	c.oauth1Callback = resolver.Resolve(c.oauth1Callback)
	c.oauth1Verifier = resolver.Resolve(c.oauth1Verifier)
	c.awsAccessKey = resolver.Resolve(c.awsAccessKey)
	c.awsSecretKey = resolver.Resolve(c.awsSecretKey)
	c.awsRegion = resolver.Resolve(c.awsRegion)
	c.awsService = resolver.Resolve(c.awsService)
	c.awsSessionToken = resolver.Resolve(c.awsSessionToken)
	return c
}

func (c authConfig) applyHeaders(req *http.Request) {
	switch c.typeID {
	case authBearer:
		if token := strings.TrimSpace(c.bearerToken); token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}
	case authBasic:
		req.SetBasicAuth(c.username, c.password)
	case authAPIKey:
		if c.apiKeyLocation == apiKeyHeader && strings.TrimSpace(c.apiKeyName) != "" {
			req.Header.Set(strings.TrimSpace(c.apiKeyName), c.apiKeyValue)
		}
	case authOAuth2AuthorizationCode:
		if token := strings.TrimSpace(c.oauthAccessToken); token != "" {
			tokenType := strings.TrimSpace(c.oauthTokenType)
			if tokenType == "" {
				tokenType = "Bearer"
			}
			req.Header.Set("Authorization", tokenType+" "+token)
		}
	}
}
